In [2]:
import numpy as np

In [61]:
arr = np.random.randint(1, 3, (3, 3))
arr1 = np.random.randint(1, 3, (3, 3))

In [64]:
arr

array([[2, 1, 2],
       [2, 2, 1],
       [2, 1, 1]], dtype=int32)

In [65]:
arr1

array([[2, 1, 2],
       [2, 1, 2],
       [2, 2, 2]], dtype=int32)

In [6]:
arr.T

array([[1, 1, 2],
       [1, 1, 2],
       [2, 2, 1]], dtype=int32)

In [ ]:
arr.flatten() #  Return of the copy an array collapset into one dimension

array([1, 1, 2, 1, 1, 2, 2, 2, 1], dtype=int32)

In [9]:
arr.ndim

2

In [10]:
arr.size

9

In [13]:
#expand the  dimension
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [14]:
arr.ndim

1

In [ ]:
np.expand_dims(arr, axis=0) # increase the dimension by 1 in the provide axis, 0 means row and 1 means colums

array([[1, 2, 3, 4]])

In [19]:
np.expand_dims(arr, axis= 1).ndim

2

In [ ]:
arr = np.zeros((3, 4)) # three row and two colums
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
arr = np.expand_dims(arr, axis=0)
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [31]:
a = np.array([[1], [2], [3]])
a

array([[1],
       [2],
       [3]])

In [32]:
a.ndim

2

In [ ]:
# squzzing the dimension by 1 dimension
np.squeeze(a) #Remove axes of length one from a.

array([1, 2, 3])

In [34]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [37]:
np.repeat(arr, 3, axis=0)
np.repeat(arr1, 3, axis=1)

array([[1, 1, 1, 2, 2, 2, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

In [38]:
a

array([[1],
       [2],
       [3]])

In [ ]:
np.roll(a, -1) # shift place

array([[2],
       [3],
       [1]])

In [43]:
c = np.array([[1,2], [3, 4], [5,6], [7, 8]])
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [44]:
np.roll(c, -1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [46]:
np.roll(c,  2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [66]:
arr + arr1

array([[4, 2, 4],
       [4, 3, 3],
       [4, 3, 3]], dtype=int32)

In [67]:
arr - arr1

array([[ 0,  0,  0],
       [ 0,  1, -1],
       [ 0, -1, -1]], dtype=int32)

In [68]:
arr * arr1

array([[4, 1, 4],
       [4, 2, 2],
       [4, 2, 2]], dtype=int32)

In [70]:
arr / arr1

array([[1. , 1. , 1. ],
       [1. , 2. , 0.5],
       [1. , 0.5, 0.5]])

In [ ]:
arr > arr1 # this is the understanding

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [72]:
c.ndim

2

In [3]:
# operation s on numpay string array
d = np.array(["Angaj", "kumar", "paswan", "gunjan"])
d

array(['Angaj', 'kumar', 'paswan', 'gunjan'], dtype='<U6')

In [4]:
np.char.upper(d) # converting all  string capital

array(['ANGAJ', 'KUMAR', 'PASWAN', 'GUNJAN'], dtype='<U6')

In [5]:
np.char.lower(d) # converting string

array(['angaj', 'kumar', 'paswan', 'gunjan'], dtype='<U6')

In [6]:
np.char.capitalize(d) # first latter capital (capitalize)

array(['Angaj', 'Kumar', 'Paswan', 'Gunjan'], dtype='<U6')

In [80]:
# mathematical function 
np.sin(arr)

array([[0.90929743, 0.84147098, 0.90929743],
       [0.90929743, 0.90929743, 0.84147098],
       [0.90929743, 0.84147098, 0.84147098]])

In [81]:
np.cos(arr)

array([[-0.41614684,  0.54030231, -0.41614684],
       [-0.41614684, -0.41614684,  0.54030231],
       [-0.41614684,  0.54030231,  0.54030231]])

In [82]:
np.log(arr)

array([[0.69314718, 0.        , 0.69314718],
       [0.69314718, 0.69314718, 0.        ],
       [0.69314718, 0.        , 0.        ]])

In [83]:
np.power(arr, 2)

array([[4, 1, 4],
       [4, 4, 1],
       [4, 1, 1]], dtype=int32)

In [84]:
np.max(arr)

np.int32(2)

In [85]:
np.min(arr)

np.int32(1)

In [87]:
np.mean(arr)

np.float64(1.5555555555555556)

In [89]:
np.var(arr)

np.float64(0.2469135802469136)

In [90]:
arr

array([[2, 1, 2],
       [2, 2, 1],
       [2, 1, 1]], dtype=int32)

In [91]:
arr1

array([[2, 1, 2],
       [2, 1, 2],
       [2, 2, 2]], dtype=int32)

In [92]:
arr - arr1

array([[ 0,  0,  0],
       [ 0,  1, -1],
       [ 0, -1, -1]], dtype=int32)

In [94]:
np.subtract(arr, arr1)

array([[ 0,  0,  0],
       [ 0,  1, -1],
       [ 0, -1, -1]], dtype=int32)

In [96]:
# sorting  and searching is numpy 
e = np.array([1, 2, 5, 4])
e

array([1, 2, 5, 4])

In [97]:
np.sort(e)

array([1, 2, 4, 5])

In [99]:
np.searchsorted(e, 4)

np.int64(2)

In [1]:
f = np.array([1, 2, 3, 4, 5, 0, 0, 0, 0]) # zero is not count
f

NameError: name 'np' is not defined

In [105]:
np.count_nonzero(f)

5

In [106]:
np.where(f)

(array([0, 1, 2, 3, 4]),)

In [107]:
np.extract(f>0, f)

array([1, 2, 3, 4, 5])

In [112]:
f.byteswap()

array([ 72057594037927936, 144115188075855872, 216172782113783808,
       288230376151711744, 360287970189639680,                  0,
                        0,                  0,                  0])

In [113]:
import numpy.matlib as np

In [114]:
np.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [115]:
np.ones([3, 4])

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [117]:
np.linalg.det(arr1)

np.float64(0.0)

In [118]:
# in matrix you can not devid by anthor matrix you have inverse
np.linalg.inv(arr)

array([[-0.5, -0.5,  1.5],
       [ 0. ,  1. , -1. ],
       [ 1. , -0. , -1. ]])