In [ ]:
# NUMPY >> NUMERICAL  PYTHON
# 2005  Travas oliphant
# Before 2005 there were special mathemetical tools (similar tora, linga)

In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.3'

In [5]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [6]:
# NUMPY >> stored the data in numpy array
#An array is container data sturcure  as use to store data as same data type >> homoginious 

In [ ]:
# why Numpy >> already we have a list c is on of the fastest programming language after c++
#  Numpy  is built using c  >> numpy  camputaion is a fast
# mathemetical computaion is fast 
# numpy array is homoginious 

In [7]:
# like this exampale
l = [1, 2, 3, "angaj", 1+4j, True]
arr = np.array(l) # Numpy.ndarray means >> n diamensonal array

In [8]:
type(arr)

numpy.ndarray

In [9]:
l1 = [1, 2, 3 ,4, 5, 6.,"Angaj"] # all output element  intger becouse  here is string in the list so 
np.array(l1)

array(['1', '2', '3', '4', '5', '6.0', 'Angaj'], dtype='<U32')

In [10]:
arr.ndim # array has only rows

1

In [11]:
arr1 = np.array([[1, 2, 3, 4],
                                  [5, 6, 7, 8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr1.ndim # here is two diamencinal array

2

In [13]:
# matrix
j = np.matrix([1, 2, 4, 5, 6])
j

matrix([[1, 2, 4, 5, 6]])

In [14]:
j.ndim

2

In [15]:
a = np.matrix([[1, 2, 3, 4, 5 ,6]]) # matrix is specialize of two diamencinal
a

matrix([[1, 2, 3, 4, 5, 6]])

In [33]:
a.ndim

2

In [16]:
a3 = np.matrix([[[1, 2], [3, 4], [5 ,6]]]) # throw an error becouse ("matrix must be 2-dimensional")
a3

ValueError: matrix must be 2-dimensional

In [35]:
arr3 = np.array([[[1,2] ,[3, 4], [5, 6]]])
arr3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [36]:
arr3.ndim

3

In [37]:
arr3[0]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
ar1 = np.array([1, 2, 3 ,4 ,5])
ar1

array([1, 2, 3, 4, 5])

In [2]:
# shallow copy  >> change in on array will lead  to change in anthor  array

In [39]:
s1 =[1, 2, 3, 4  ,5]
np.asarray(s1)

array([1, 2, 3, 4, 5])

In [40]:
type(s1)

list

In [41]:
np.asanyarray([1, 2 , 3 ,4 , 5 , 6])

array([1, 2, 3, 4, 5, 6])

In [45]:
t = ([1, 2], [3, 4], [5, 6])
t
type(t)

tuple

In [46]:
np.array(t)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
ar1

array([1, 2, 3, 4, 5])

In [58]:
ar1[2]
ar1[2]

np.int64(3)

In [62]:
# append
ar1[0] 
ar1

array([30,  2,  3,  4,  5])

In [ ]:
np.fromfunction(lambda i ,j: i==j, (3,3))


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [25]:
arr1 = np.fromfunction(lambda i ,j: i==j, (3,4))
arr1

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [26]:
arr1[0]
arr1[2]
arr1.ndim

2

In [27]:
arr1.shape # shape of array

(3, 4)

In [28]:
arr1.size

12

In [38]:
arrr3 = np.fromfunction(lambda i,  j:  i*j,  (3,4))
arrr3

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.]])

In [39]:
arrr3.ndim

2

In [40]:
arrr3.size

12

In [41]:
arrr3

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.]])

In [46]:
arrr3.reshape(2, 6)

array([[0., 0., 0., 0., 0., 1.],
       [2., 3., 0., 2., 4., 6.]])

In [48]:
arrr3.reshape(1, 12)

array([[0., 0., 0., 0., 0., 1., 2., 3., 0., 2., 4., 6.]])

In [49]:
arrr3.reshape(12, 1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [2.],
       [4.],
       [6.]])

In [50]:
arrr3.reshape(3, -1)

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.]])

In [ ]:
arrr3.reshape(12, 1). base # to see the orignal array

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.]])

In [ ]:
arrr3.reshape(2, 2, 3) # multiaplication should be equal to array size 

array([[[0., 0., 0.],
        [0., 0., 1.]],

       [[2., 3., 0.],
        [2., 4., 6.]]])

In [ ]:
# condition array
arr4 =  np.random.randint(1, 10, (5, 6))
arr4

array([[9, 4, 5, 9, 4, 8],
       [9, 3, 8, 7, 1, 2],
       [3, 1, 4, 4, 8, 7],
       [9, 9, 6, 4, 2, 8],
       [6, 5, 1, 9, 6, 4]], dtype=int32)

In [70]:
arr4.size # 30
arr4.shape
arr4.ndim


2

In [ ]:
arr4 > 3

array([[ True,  True,  True,  True,  True,  True],
       [ True, False,  True,  True, False, False],
       [False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True],
       [ True,  True, False,  True,  True,  True]])

In [72]:
arr4[0]

array([9, 4, 5, 9, 4, 8], dtype=int32)

In [56]:
arrr3.reshape(1, 2, 2, 3).ndim

4

In [74]:
arr4[0] [3]

np.int32(9)

In [75]:
arr4

array([[9, 4, 5, 9, 4, 8],
       [9, 3, 8, 7, 1, 2],
       [3, 1, 4, 4, 8, 7],
       [9, 9, 6, 4, 2, 8],
       [6, 5, 1, 9, 6, 4]], dtype=int32)

In [76]:
arr4[3] [4]

np.int32(2)

In [77]:
arr4[0:3]

array([[9, 4, 5, 9, 4, 8],
       [9, 3, 8, 7, 1, 2],
       [3, 1, 4, 4, 8, 7]], dtype=int32)

In [79]:
arr4

array([[9, 4, 5, 9, 4, 8],
       [9, 3, 8, 7, 1, 2],
       [3, 1, 4, 4, 8, 7],
       [9, 9, 6, 4, 2, 8],
       [6, 5, 1, 9, 6, 4]], dtype=int32)

In [80]:
arr4[0:3, 1:3]

array([[4, 5],
       [3, 8],
       [1, 4]], dtype=int32)

In [83]:
arr4

array([[9, 4, 5, 9, 4, 8],
       [9, 3, 8, 7, 1, 2],
       [3, 1, 4, 4, 8, 7],
       [9, 9, 6, 4, 2, 8],
       [6, 5, 1, 9, 6, 4]], dtype=int32)

In [82]:
arr4[0:3, [1 ,3]]

array([[4, 9],
       [3, 7],
       [1, 4]], dtype=int32)

In [89]:
#mathemetical operation on two array
arr5 = np.random.randint(1,  3, (3, 3))
arr6 = np.random.randint(1,  3, (3, 3))

In [90]:
arr5 

array([[2, 2, 2],
       [2, 2, 1],
       [1, 2, 1]], dtype=int32)

In [92]:
arr6

array([[2, 2, 2],
       [2, 2, 2],
       [1, 2, 2]], dtype=int32)

In [ ]:
arr5+arr6 # indexing by array addition (add.., sub..., multi.... , devision )


array([[4, 4, 4],
       [4, 4, 3],
       [2, 4, 3]], dtype=int32)

In [96]:
0/arr5
arr5/0

C:\Users\angaj\AppData\Local\Temp\ipykernel_19680\4107735119.py:2: RuntimeWarning: divide by zero encountered in divide
  arr5/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
# but @ is a multiaplication
arr5 @ arr6

array([[10, 12, 12],
       [ 9, 10, 10],
       [ 7,  8,  8]], dtype=int32)

In [83]:
for i in range(5):
    print(i)

0
1
2
3
4


In [2]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [3]:
(i for i in range(5))

<generator object <genexpr> at 0x000001CBFF856800>

In [4]:
np. fromstring("22, 33 , 44", sep = " ")

C:\Users\angaj\AppData\Local\Temp\ipykernel_19680\3665775889.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np. fromstring("22, 33 , 44", sep = " ")


array([22.])

In [5]:
np. fromstring('22, 33 , 44', sep = " ", dtype= int)

C:\Users\angaj\AppData\Local\Temp\ipykernel_19680\920872461.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np. fromstring('22, 33 , 44', sep = " ", dtype= int)


array([22])

In [6]:
np.arange(1, 10, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [7]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [13]:
z.reshape(12, 1). base

NameError: name 'z' is not defined

In [98]:
# tanspose  >>converting rows to columns and colms to row 
arr6

array([[2, 2, 2],
       [2, 2, 2],
       [1, 2, 2]], dtype=int32)

In [99]:
arr6.T

array([[2, 2, 1],
       [2, 2, 2],
       [2, 2, 2]], dtype=int32)