In [1]:
import numpy as np

In [2]:
np.zeros(5) # but this is the float

array([0., 0., 0., 0., 0.])

In [3]:
a = np.zeros(5, dtype= int) # not print float  just print int number
a

array([0, 0, 0, 0, 0])

In [5]:
a.ndim

1

In [7]:
np.zeros((3,4), dtype= int )

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
a = np.ones(3, dtype=int)
b = np.array([[2,3], [4, 5]])
b

array([[2, 3],
       [4, 5]])

In [15]:
a.ndim
b.ndim

2

In [22]:
# 3D diamencnal array
a = np.zeros([1, 3, 4], dtype= int)
a # that is  3D array

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [27]:
b = np.zeros((3, 3, 4))
b

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [28]:
b.ndim

3

In [31]:
# 4D
np.zeros((1, 1, 3, 3))
# 5D
np.zeros((1, 1, 1, 3, 4))

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [35]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
# Adding
a+5



array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
a*2


array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [47]:
a.ndim

2

In [49]:
s1 = np.zeros((3, 4))
s1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
s1+2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [51]:
s1*3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
arr = s1+5
arr

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [54]:
arr*2

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [55]:
arr-1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [57]:
arr1 = arr
arr1

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [58]:
np.empty((3, 4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [65]:
# random moduls
import random


In [ ]:
random.choice("Angaj")
random.choice("Angaj")
random.choice("Angaj")


'g'

In [70]:
random.choice("Angaj")
random.choice("Angaj")
random.choice("Angaj")

'j'

In [71]:
random.randrange(1, 10)

9

In [74]:
lis = [1, 2, 3, 4]
lis

[1, 2, 3, 4]

In [76]:
random.shuffle(lis)
lis

[2, 4, 3, 1]

In [77]:
np.random.rand(3, 4)

array([[0.11717301, 0.82107185, 0.4616939 , 0.9609923 ],
       [0.47659553, 0.54954725, 0.23075623, 0.30799814],
       [0.85579209, 0.94386191, 0.19884994, 0.07939413]])

In [78]:
np.random.rand(2, 3)

array([[0.2794026 , 0.11625076, 0.07463416],
       [0.03705744, 0.47997769, 0.97585599]])

In [82]:
np.random.randint(1, 4, size = (3, 3))

array([[1, 1, 3],
       [3, 2, 3],
       [3, 1, 2]], dtype=int32)