In [5]:
# here is my some importent laburay for statistics and probabilty
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [7]:
# chi square test 
data = sns.load_dataset('tips')
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [9]:
data[["sex", "smoker"]]

sex smoker
0    Female     No
1      Male     No
2      Male     No
3      Male     No
4    Female     No
..      ...    ...
239    Male     No
240  Female    Yes
241    Male    Yes
242    Male     No
243  Female     No

[244 rows x 2 columns]

In [14]:
# sumarisation of data using crosstab
data_table = pd.crosstab(data['sex'], data['smoker'])
data_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [15]:
observed_value = data_table.values

In [16]:
observed_value

array([[60, 97],
       [33, 54]], dtype=int64)

In [26]:
import scipy.stats as stats

stats_test, p, dof, expected_value = stats.chi2_contingency(observed_value)

In [27]:
expected_value

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [29]:
# using chisquare critical method
dof = 1

In [30]:
from scipy.stats import chi2

In [34]:
for i in zip(observed_value, expected_value):
    print(i)

(array([60, 97], dtype=int64), array([59.84016393, 97.15983607]))
(array([33, 54], dtype=int64), array([33.15983607, 53.84016393]))


In [37]:
chisquare_test = sum([(0-e)**2/e for  e, e in zip(observed_value, expected_value)])

In [38]:
chisquare_test

array([ 93., 151.])

In [39]:
chisquare_stats = chisquare_test[0] + chisquare_test[1]

In [40]:
chisquare_stats

244.0

In [43]:
alpha = 0.05

In [46]:
chi2_critical = chi2.ppf(1 - alpha, dof)

In [47]:
chi2_critical

3.841458820694124

In [48]:
if chisquare_stats >= chi2_critical:
    print("Reject the null hpothesis, thre is a relationship between two categorical variables")
else:
    print("fail to reject null hypothesis, no relationship")

Reject the null hpothesis, thre is a relationship between two categorical variables


In [50]:
# p value method
p_value = 1-chi2.cdf(x = chisquare_stats, df = dof)

In [51]:
p_value

0.0

In [52]:
if p_value <= 0.05:
    print("Reject the null hpothesis, thre is a relationship between two categorical variables")
else:
    print("fail to reject null hypothesis, no relationship")

Reject the null hpothesis, thre is a relationship between two categorical variables


In [53]:
# num of hours student study daily and wekly basic
# monday, tuesday...., sunday

expected_data = [8, 5, 6, 8, 5, 7, 6]
observed_data = [7, 4, 7, 9, 4, 8, 6]

sum(expected_data), sum(observed_data)

(45, 45)

In [55]:
chisqstats, pvalue = stats.chisquare(observed_value, expected_value)

In [74]:
# using chisquare critical
critical_value = stats.chi2.ppf(1-alpha, dof)

In [75]:
chisqstats

0.001934818536627623

In [ ]:
chisqstats = chisqstats[0] + chisqstats[1]

In [80]:
if chisqstats > critical_value:
    print("Reject the null hypothesis")
else:
    print("fail to reject")

fail to reject


In [81]:
# F test
# Two workers >> if one worker is more effective than other one

worker1 = [14, 23, 41, 56, 67, 76]
worker2 = [13, 24, 35, 56, 47, 45]

In [84]:
fstats = np.var(worker1) / np.var(worker2)
fstats

2.370811518324608

In [94]:
df1 = len(worker1)-1
df2 = len(worker2) - 3

In [95]:
df1
df2

3

In [97]:
stats.f.ppf(q = 1-alpha, dfn=df1, dfd = df2)

9.01345516752258

In [98]:
if fstats>critical_value:
    print("Reject the null hypothisis")

else:
    print("Fail to reject null hypothesis")

Fail to reject null hypothesis


In [ ]:
# Anova Test >> compare means of two or more than two sample.
# Null Hypothesis 

In [106]:

# Sample data
data = {
    'Plant': ['Rose', 'Tulip', 'Sunflower', 'Lily', 'Marigold'],
    'Color': ['Red', 'Yellow', 'Yellow', 'White', 'Orange'],
    'Height_cm': [45, 30, 150, 60, 35],
    'Perennial': [True, False, True, True, False]
}

# Create DataFrame
df = pd.DataFrame(data)

# Show the DataFrame
print(df)


       Plant   Color  Height_cm  Perennial
0       Rose     Red         45       True
1      Tulip  Yellow         30      False
2  Sunflower  Yellow        150       True
3       Lily   White         60       True
4   Marigold  Orange         35      False


In [ ]:
df = pd.read_csv('plant.csv')
